//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Helpdesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Technician { get; set; }
        public string AdminBy { get; set; }
        public System.DateTimeOffset DueDate { get; set; }
        public System.DateTimeOffset OnProgressDate { get; set; }
        public System.DateTimeOffset OnWaitingDate { get; set; }
        public System.DateTimeOffset OnHoldingDate { get; set; }
        public System.DateTimeOffset ResolvedDate { get; set; }
        public string Status { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public System.DateTimeOffset UpdateDate { get; set; }
        public System.DateTimeOffset DeleteDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> DueDates_Id { get; set; }
        public Nullable<int> SubCategories_Id { get; set; }
        public Nullable<int> users_Id { get; set; }
    
        public virtual DueDate DueDate1 { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual User User { get; set; }
    }
}
